spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.210.100.17:3306/db_tsp_common_data?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Bnqc@2020
    druid:    # 初始化大小、最小、最大连接数 wall,
      initial-size: 1
      min-idle: 3
      max-active: 20
      max-wait: 60000   # 配置获取连接等待超时的时间
      stat-view-servlet:  # 监控后台账号和密码
        login-username: user
        login-password: 1234
      filter:  # 配置 StatFilter
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      validation-query: select 'x'
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      min-evictable-idle-time-millis: 30000  # 配置一个连接在池中最小生存的时间，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      filters: stat,slf4j      # 配置监控统计拦截的filters
  cloud:
    nacos:
      discovery:
        server-addr: http://10.210.100.17:8848
---
spring:
  redis:
    host: 10.210.100.17
    password: Bnqc@2020
    port: 6379
    timeout: 3000
    lettuce:
      pool:
        max-active: 1000
        max-idle: 100
        min-idle: 10
        max-wait: 3000

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.bnmotor.icv.tsp.common.data.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

adam:
  logging:
    config: classpath:logger/log4j2-dev.xml
    path: /logs
    level:
      com.bnmotor.icv.tsp: debug
      org.springframework.web: debug
